"""Fixed collaborator relationship

Revision ID: ba1700397ec0
Revises: 93ede0c3f0a5
Create Date: 2024-07-30 22:10:26.976481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba1700397ec0'
down_revision = '93ede0c3f0a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_collaborators', schema=None) as batch_op:
        batch_op.alter_column('pdf_document_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=32),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=32),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('document_collaborators', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.String(length=32),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('pdf_document_id',
               existing_type=sa.String(length=32),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
