apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: test
type: Opaque
data:
  AWS_ACCESS_KEY_ID: QUtJQTNGTEQ1UTVTUlpUVERVUVk=
  AWS_SECRET_ACCESS_KEY: RDhxdVhxS01sVFR0S09Xb2NOeUdqS2FtVjQ1d0s2Z2lOUE1QMkNQbw==
  SECRET_KEY: MWgyYXhXU0RaQWhWZmRJek5nb04zRHJORUhaM1NXckFJcGxyQkQ5M3Q1Rw==
  DATABASE_URL: cG9zdGdyZXNxbDovL3Rlc3R1c2VyOnpSNlBNdGZ3UUpkTm8xRUNnNVd6T0s3b016czNHQndmQGRiOjU0MzIvdGVzdGRi
